### ISSUE TITLE
BUG: provider does not support all the languages that SonarQube supports

### ISSUE THREAD

**Issue by tbutler-qontigo** [jdamata/terraform-provider-sonarqube#101]
Hi there,

### Terraform Version
1.3.2

### Affected Resource(s)
- sonarqube_qualityprofile

### Expected Behavior
I should be able to create a profile for any language that SonarQube supports

### Actual Behavior
The provider only supports a subset:
```go
[]string{"cs", "css", "flex", "go", "java", "js", "jsp", "kotlin", "php", "py", "ruby", "scala", "ts", "vbnet", "web", "xml"},
```

so attempting to use terraform for example will result in:
```
expected language to be one of [cs css flex go java js json jsp kotlin php py ruby scala ts vbnet web xml], got terraform
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform apply` any sonarqube_qualityprofile for the language "terraform"

### References
The offending line of code is here: https://github.com/jdamata/terraform-provider-sonarqube/blob/5632f79332622b472cafcb6c01592a24eddd0ad4/sonarqube/resource_sonarqube_qualityprofile.go#L92

#### Simply add the missing languages
This is simply a matter of extending the list but has the following disadvantages
1. you have to keep updating the provider as more languages are supported.
2. Some editions of SonarQube may not support all languages

#### Dynamically validate the list.
If you retrieve the list of supported languages from `/api/languages/list` then you can validate it is one of these.
Disadvantage: This may be non-trivial (or not possible at all) with an SDK plugin but should be using the new framework mode.

#### Remove the check completely.
This would seem to be the simplest option with few downsides
Here, an error still occurs but it is an API error at apply time rather than a validation error.
From a consumer perspective, there is little different - the error would look like this:
```
API returned an error: Value of parameter 'language' (bob) must be one of: [cloudformation, cs, css, flex, go, java, js, json, jsp, kotlin, kubernetes, php, py, ruby, scala, terraform, text, ts, vbnet, web, xml, yaml]
```
(Here I used "bob" as the language since terraform actually is supported).

And the operation fails as expected.

**This is the preferred option IMO since we are allowing SonarQube itself to decide what it does/does not support**

**Comment by jdamata** [comment]
Removing the validation makes sense to me. Thank you for the detailed report. 

Did you want to open a pr for this :) ?

**Comment by jdamata** [comment]
Fixed in https://github.com/jdamata/terraform-provider-sonarqube/pull/102

**Comment by tbutler-qontigo** [comment]
> Removing the validation makes sense to me. Thank you for the detailed report.
> 
> Did you want to open a pr for this :) ?

I was waiting to see which option you would go for :)
Thanks for fixing.
