### ISSUE TITLE
Add feature to assign custom "quality gate" manage permission to specific user or group

### ISSUE THREAD

**Issue by noor409** [jdamata/terraform-provider-sonarqube#109]
Hi ,

Am able to assign custom quality gates manage permission to specific user/ group via UI, 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/56771776/209113046-67fd1432-98ef-4136-b301-3c2b30ccdd6a.png">

**Comment by EvertonSA** [comment]
let me clarify on this one because this description is not very clean,

I as a Sonarqube administrator would like to create a custom quality gate per team I'm managing and assign key users of that team to manage the quality gate. 

On the UI, we can assign a Quality Gate to a person, and that person is capable of administer the quality gate rules by then selfs. On this terraform module, it seems not possible.


Can we have this implemented?

**Comment by jdamata** [comment]
Is this possible with the sonarqube api? 


You can assign users the 'gateadmin' role via sonarqube_permissions but i believe this is a global permission not project scoped.

IE: `https://github.com/jdamata/terraform-provider-sonarqube/blob/668f89406ac98f3fba565c92e14335f897dd83bf/docs/resources/sonarqube_permissions.md#example-set-codeviewer--user-permissions-on-project-level-for-a-user-called-johndoe`

**Comment by EvertonSA** [comment]
@jdamata it seems to be:
![image](https://user-images.githubusercontent.com/30481051/209927989-12f2d06b-dd13-444e-9175-ba2509cfa08e.png)

![image](https://user-images.githubusercontent.com/30481051/209928019-c366a0d6-250e-4f67-8c1e-02bdb168168e.png)

but it does not show on the docs on http://localhost:8000/web_api/api/qualitygates

from my understanding, it's a POST on /api/qualitygates/add_user with   --data-raw 'gateName=<QUALITY_GATE_NAME>&login=<USER_ID>'

**Comment by EvertonSA** [comment]
I also tested for groups and the API is the same:

it's a POST on /api/qualitygates/add_user with --data-raw 'gateName=<QUALITY_GATE_NAME>&login=<GROUP_ID>'

![image](https://user-images.githubusercontent.com/30481051/209929185-a8e1bb6b-ca70-4c66-a176-6553c8ec053f.png)

**Comment by EvertonSA** [comment]
perhaps we should have a `sonarqube_qualitygate_usergroup_association` resource?

**Comment by jdamata** [comment]
Thanks for the investigation @EvertonSA. I was able to find this in the web_api docs. This api is marked as an 'internal' api.

```
Use at your own risk; internal services are subject to change or removal without notice.
```

![Screen Shot 2022-12-29 at 11 42 08 AM](https://user-images.githubusercontent.com/33775101/209983221-596b2255-60c0-4c95-9b06-d829616a1749.png)

**Comment by EvertonSA** [comment]
@jdamata I would like to work on this, do you consider a `sonarqube_qualitygate_usergroup_association` a good approach or would you do something different?

**Comment by jdamata** [comment]
Yah that resource sounds good. I'm a little concerned that this API might change significantly. Please be sure to add acceptance tests with the new resource

**Comment by EvertonSA** [comment]
this issue can be closed
