### ISSUE TITLE
Support GitLab ALM APIs

### ISSUE THREAD

**Issue by jwilliams-fn** [jdamata/terraform-provider-sonarqube#117]
SonarQube supports multiple DevOps integrations (e.g.: GitHub, GitLab, Azure, etc). Configuring these integrations through terraform would be incredibly useful.

- [alm_settings API](https://next.sonarqube.com/sonarqube/web_api/api/alm_settings)
- [alm_integrations API](https://next.sonarqube.com/sonarqube/web_api/api/alm_integrations)

These integrations require a SonarQube developer edition or higher installation.

**Comment by ViktorLindgren95** [comment]
This would be a godsent we are currently modifying both project branches and ALM settings via http terraform provider and its very much dirty

**Comment by jwilliams-fn** [comment]
I would not mark this issue as complete. There are many more ALM APIs to implement. The ones for my specific use case are also still unimplemented:
- [api/alm_settings/create_gitlab](https://next.sonarqube.com/sonarqube/web_api/api/alm_settings/create_gitlab)
- [api/alm_settings/set_gitlab_binding](https://next.sonarqube.com/sonarqube/web_api/api/alm_settings/set_gitlab_binding)
- [api/alm_settings/update_gitlab](https://next.sonarqube.com/sonarqube/web_api/api/alm_settings/update_gitlab)

**Comment by jdamata** [comment]
Can you update the title on this issue to be specific to the alm api that you are needing (gitlab). We should probably have different issues for each type of alm that needs implementation.

**Comment by jdamata** [comment]
https://github.com/jdamata/terraform-provider-sonarqube/pull/126
