### ISSUE TITLE
Support creating a Quality Gate by copying existing Quality Gate

### ISSUE THREAD

**Issue by felixlut** [jdamata/terraform-provider-sonarqube#131]
Currently the [`sonarqube_qualitygate`](https://registry.terraform.io/providers/jdamata/sonarqube/latest/docs/resources/sonarqube_qualitygate) resource only supports two inputs (`name` and `is_default`). 

It would be nice to be able to create Quality Gates by copying an existing gate, just as the `Copy` button in the UI (see image below), or the `api/qualitygates/copy` endpoint. 

![bild](https://user-images.githubusercontent.com/34520175/221381217-e8ddda3c-b295-419c-a553-a8065c24d8c4.png)

My proposed solution is to add an extra argument (`copy_from`) to the `sonarqube_qualitygate` resource to support copying an existing gate.

**Comment by felixlut** [comment]
I can work on this

**Comment by jdamata** [comment]
Sounds good to me. I've assigned this to you. Please be sure to update the docs and add a test case for this parameter. 

Thanks!

**Comment by jdamata** [comment]
Thanks you @felixlut for your work on this. Ive cut a new release with this feature.
