### ISSUE TITLE
Typo in token environment variable

### ISSUE THREAD

**Issue by jwilliams-fn** [jdamata/terraform-provider-sonarqube#135]
https://github.com/jdamata/terraform-provider-sonarqube/blob/ec4579f5c7dc171b72c9410e1fa48a7a0b6c220a/sonarqube/provider.go#L40

Should be `SONARQUBE_TOKEN` not `SONRQUBE_TOKEN`.

**Comment by jdamata** [comment]
Wow. How has this typo been in here for so long. Thanks for that catch!
