### ISSUE TITLE
Unable create gitlab binding Sonarqube version: 9.9.0 community

### ISSUE THREAD

**Issue by daemondev** [jdamata/terraform-provider-sonarqube#137]
Hi there,

Thank you for opening an issue.

### Terraform Version
Sonarqube version: 9.9.0
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.59.0
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/vsphere v2.2.0
+ provider registry.terraform.io/jdamata/sonarqube v0.15.11

### Affected Resource(s)
Please list the resources as a list, for example:
- sonarqube_gitlab_binding
- sonarqube_project

### Terraform Configuration Files
```hcl
sonarqube_gitlab_binding.gitlab-binding: Creating...
╷
│ Error: API returned an error: Unknown url : /api/alm_settings/set_gitlab_binding
│ 
│   with sonarqube_gitlab_binding.gitlab-binding,
│   on integration.tf line 13, in resource "sonarqube_gitlab_binding" "gitlab-binding":
│   13: resource "sonarqube_gitlab_binding" "gitlab-binding" {
│ 
╵
ERRO[0026] 1 error occurred:
        * exit status 1

```

### Expected Behavior
create binding

### Actual Behavior
error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by daemondev** [comment]
Gitlab community 15

**Comment by jdamata** [comment]
What version of sonarqube are you using?

**Comment by daemondev** [comment]
@jdamata Sonarqube version: 9.9.0
![image](https://user-images.githubusercontent.com/4111039/224528945-1f7c01d7-2b9c-4c78-88c0-2dc44108bcbb.png)

**Comment by jdamata** [comment]
Are you able to configure this manually via these steps? https://docs.sonarqube.org/latest/devops-platform-integration/gitlab-integration/#importing-your-gitlab-projects-into-sonarqube

Maybe the community version you are using is not supported for this? The CI for this project uses the sonarqube:developer docker image.

**Comment by daemondev** [comment]
@jdamata then, what sonar (version  community)  is full compatible with terraform-provider-sonarqube ?

**Comment by jdamata** [comment]
Some of the features supported by this provider are only available in the developer edition of sonarqube.

**Comment by jdamata** [comment]
> Are you able to configure this manually via these steps? https://docs.sonarqube.org/latest/devops-platform-integration/gitlab-integration/#importing-your-gitlab-projects-into-sonarqube
> 
> Maybe the community version you are using is not supported for this? The CI for this project uses the sonarqube:developer docker image. 

Were you able to configure this manually? If not, I don't think this is an issue with the terraform provider and I'll close this issue
