### ISSUE TITLE
provider specific proxy config option

### ISSUE THREAD

**Issue by kaiehrhardt** [jdamata/terraform-provider-sonarqube#139]
Hi,

it would be nice a have a provider specific proxy config option. (for example like aws provider https://registry.terraform.io/providers/hashicorp/aws/latest/docs#http_proxy)

I know in the current version it's possible via env vars, but running in a large stack it effects every provider and can cause problems.

Do you think, there's any chance to implement this?

Thank you already in advance.

**Comment by jdamata** [comment]
Can that be achieved using this: https://github.com/jdamata/terraform-provider-sonarqube/blob/master/examples/basic/main.tf#L12

**Comment by kaiehrhardt** [comment]
The sonarqube host url? O.o

**Comment by jdamata** [comment]
Maybe my understanding of the http_proxy field in the aws provider is wrong. From what I can tell, that property allows you to call the AWS api from a proxy you specify instead of directly. If you wanted to achieve the same thing here, you could specify the sonarqube host url as the proxy you want to call instead.

**Comment by jdamata** [comment]
@kaiehrhardt did sonarqube host url work?

**Comment by kaiehrhardt** [comment]
> Maybe my understanding of the http_proxy field in the aws provider is wrong. From what I can tell, that property allows you to call the AWS api from a proxy you specify instead of directly. If you wanted to achieve the same thing here, you could specify the sonarqube host url as the proxy you want to call instead.

I'm pretty sure, that won't work. You still need a target url to route from proxy to sonarqube.
