### ISSUE TITLE
Add support for quality profiles

### ISSUE THREAD

**Issue by jdamata** [jdamata/terraform-provider-sonarqube#16]

**Comment by DevOps575** [comment]
@jdamata - Is there any plan to have to this feature available soon?

**Comment by jdamata** [comment]
Hi,

Recently I've been trying to get more coverage on acceptance tests with the resources that is already supported, this work is almost done. Afterwards I planned on getting this and the other three resources finished up and releasing the first beta version of this provider. 

As for a timeline, i'm not sure i can give an accurate one. I've been quite busy with my day job and life. You can subscribe to this issue for updates. 

Ill also add a helm wanted label, in case anyone else wanted to pick up any of the issues for adding more resources

**Comment by DevOps575** [comment]
Thanks Joel.

**Comment by DevOps575** [comment]
@jdamata - Thanks for adding support for qualityprofile. Is there any way to export qualityprofile key as well?

**Comment by jdamata** [comment]
should be able to reference quality profile key like so:

sonarqube_qualityprofile.main.id OR sonarqube_qualityprofile.main.key

**Comment by DevOps575** [comment]
Thanks Joel. I had tried that but giving below error:

This object has no argument, nested block, or exported attribute named "key". When i specify the ID it gives its value 0.

**Comment by jdamata** [comment]
> Thanks Joel. I had tried that but giving below error:
> 
> This object has no argument, nested block, or exported attribute named "key". But sonarqube_qualityprofile.main.id is working fine .

Are you on the latest version? I do think key should be working. Using id makes more sense anyways IMO.

Also, yesterday i published this provider to the terraform registry so that installing and updating the provider is much easier: https://registry.terraform.io/providers/jdamata/sonarqube/latest
