### ISSUE TITLE
Add datasource groups and qualitygate

### ISSUE THREAD

**Issue by estebangit** [jdamata/terraform-provider-sonarqube#167]
Hi,
thank you for the job you do on this great provider!

I have a use case where I need a datasource for “sonarqube_group” and “sonarqube_qualitygate”.

### Affected Resource(s)
- sonarqube_group
- sonarqube_qualitygate

```hcl
data “sonarqube_group” “my_global_group” {
	name = “MyGroup”
}

data “sonarqube_qualitygate” “my_custom_gate” {
	name = “MyGate”
}

```
How can I contribute?

Regards,
Esteban

**Comment by jdamata** [comment]
Sounds good to me. Did you want to work on this? An example of a data source would be https://github.com/jdamata/terraform-provider-sonarqube/blob/master/sonarqube/data_source_sonarqube_user.go
