### ISSUE TITLE
Provider versions jdamata/sonarqube >=0.15.12 not compatible with sonarqube Data Center edition

### ISSUE THREAD

**Issue by Malgosiatobiasz1** [jdamata/terraform-provider-sonarqube#180]
Provider versions jdamata/sonarqube >=0.15.12 not compatible with sonarqube Data Center edition. Endpoint api/system/info does not have the Version key used by the provider. May I ask you to improve this? Below version 0.15.11 inclusive provider uses endpoint /api/server/version , then it is compatible with sonarqube-dce, could it be restored?

**Comment by Malgosiatobiasz1** [comment]
Hi @jdamata ,
will provider in versions >=0.15.12 be compatible with sonarqube dce edition? Are you not planning to do anything about it? Thank you in advance for the information.

**Comment by jdamata** [comment]
What version of Sonarqube Data Center are you running?

**Comment by Malgosiatobiasz1** [comment]
Hi, I am using sonarqube-dce 9.9

czw., 27 lip 2023, 17:07 użytkownik Joel Damata ***@***.***>
napisał:

**Comment by Malgosiatobiasz1** [comment]
Hi @jdamata Can you roughly tell me when I can expect the provider to be updated to support the sonarqube dce edition?

**Comment by jdamata** [comment]
I haven't had time to look into this recently. I'll try to find some time this weekend to gauge how much work is actually involved

**Comment by Malgosiatobiasz1** [comment]
@jdamata thank you very much.

**Comment by jdamata** [comment]
@Malgosiatobiasz1 took an initial stab to get a sense of the effort here: https://github.com/jdamata/terraform-provider-sonarqube/pull/183/files. 

Configuring installed_version and installed_edition should hopefully get you unblocked for using most of the provider. I think there are some api discrepancies with the datacenter edition but hopefully they are not too many.

**Comment by jdamata** [comment]
All tests actually passed for DCE lts and latest  versions: https://github.com/jdamata/terraform-provider-sonarqube/pull/183. You should be good after configuring the provider with installed_version and installed_edition

**Comment by Malgosiatobiasz1** [comment]
Thanks a lot @jdamata
