### ISSUE TITLE
Add support for webhooks

### ISSUE THREAD

**Issue by jdamata** [jdamata/terraform-provider-sonarqube#19]

**Comment by nicoangelo** [comment]
Hi!
I would be very interested in helping out with this. I can open a PR in a few days, need to clarify a few things first.

Furthermore my use case also requires this to work on SonarQube 7.9. Should I open another issue so that we can look into supporting different versions of SQ?

**Comment by jdamata** [comment]
Hi @nicoangelo! 

Yep please open a new issue for the 7.9 support

At a minimum this would involve:

-  changing the minimum version of sonarqube here: https://github.com/jdamata/terraform-provider-sonarqube/blob/07dbbe501c6e86861a860073ab3e97f6399aa71e/sonarqube/provider.go#L118

- running the acceptance tests against sonarqube version 7.9: https://github.com/jdamata/terraform-provider-sonarqube/blob/07dbbe501c6e86861a860073ab3e97f6399aa71e/Makefile#L20

**Comment by jdamata** [comment]
I ran the acceptance test against version 7.9-community and there were quite a few failures. Some work needs to be done to support version 7.9

```
FAIL
coverage: 55.5% of statements
FAIL    github.com/jdamata/terraform-provider-sonarqube/sonarqube       37.708s
FAIL1
```

**Comment by nicoangelo** [comment]
Quick heads-up: I'm still working on this. Already pushed the code, but still need to add tests.

**Comment by jdamata** [comment]
I've added support for sonarqube 7.9 LTS, you may need to rebase your branch.

**Comment by jdamata** [comment]
Thanks @mrparkers. I pushed git tag v0.0.4 with this change.
