### ISSUE TITLE
Error in the documentation on the terraform page

### ISSUE THREAD

**Issue by humpalu** [jdamata/terraform-provider-sonarqube#199]
Hi there,

Thank you for opening an issue.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v1.4.5

### Expected Behavior
What should have happened?

sonarqube_qualityprofile_project_association should be created

### Actual Behavior
The example on the follwing page https://registry.terraform.io/providers/jdamata/sonarqube/latest/docs/resources/sonarqube_qualityprofile_project_association

has an error in the example in this block

```
resource "sonarqube_qualityprofile_project_association" "main" {
    quality_profile = sonarqube_qualityprofile.main.name
    project         = sonarqube_project.main.name
    language        = "js"
}
```
should be
```
resource "sonarqube_qualityprofile_project_association" "main" {
    quality_profile = sonarqube_qualityprofile.main.name
    project         = sonarqube_project.main.project
    language        = "js"
}
```

since the project association should be mapped to sonarqube_project.project

**Comment by humpalu** [comment]
Another Typo on the https://registry.terraform.io/providers/jdamata/sonarqube/latest/docs/resources/sonarqube_new_code_periods page

```
resource "sonarqube_new_code_period" "reference" {
  project = sonarqube_project.reference.project
  type = "REFERENCE_BRANCH"
  value = "main"
```
should be

```
resource "sonarqube_new_code_periods" "reference" {
  project = sonarqube_project.reference.project
  type = "REFERENCE_BRANCH"
  value = "main"
}
```

**Comment by jdamata** [comment]
@humpalu Thanks! Fixed here: https://github.com/jdamata/terraform-provider-sonarqube/commit/1fd2cf0ff580566647c5a841448046e07e4f300a
