### ISSUE TITLE
Looking for an additional maintainer

### ISSUE THREAD

**Issue by jdamata** [jdamata/terraform-provider-sonarqube#212]
Hello,

I think it would be beneficial to have an additional person who can review/merge/release the provider. Just in case I'm not available for an extended period of time. It would also be nice to have someone review my PRs :)

I will still be active and plan to always be active here.

If you have previously contributed to this provider and are interested. Please let me know.

**Comment by freeranger** [comment]
@jdamata I wouldn't be adverse to the idea...just be careful what you wish for :)
I don't do GO day to day but I have contributed a few times and have been a developer since the dawn of time....
