### ISSUE TITLE
Regarding: SonarCloud Terraform-Go Code

### ISSUE THREAD

**Issue by nishantabanik** [jdamata/terraform-provider-sonarqube#24]
Hi @jdamata ,

As per our mail conversations regarding: SonarCloud Terraform-Go Code conversation from your SonarQube related code, Will you be fine if we fork your repository & do the required changes for SonarCloud?
Please approve so that I can go ahead & start doing the required changes for SonarCloud requirement.
I have also replied for your mail. I'll wait for your response.

Thanks again!!

Regards,
Nishanta Banik

**Comment by jdamata** [comment]
Of course. Happy coding!

**Comment by jkumar19** [comment]
@jdamata  - Thanks. @nishantabanik I had discussion with Joel to take his code and add sonarcloud support on the top of that. I have rolled out a separate terraform release for sonarcloud which is available for community. You can also use the same release. Joel thanks again for your support. I think we should close this issue.

**Comment by em-jones** [comment]
@jkumar19 or @jdamata - I'm having a difficult time finding the results of this fork. Is there a separate provider? If so, can I trouble y'all for a point in the right direction?

Thanks!

**Comment by jdamata** [comment]
I was never able to find the fork either. Not sure if related but someone else has done some work for a sonarcloud provider https://github.com/rewe-digital/terraform-provider-sonarcloud
