### ISSUE TITLE
[Feature] Copy profile and deactivate rules

### ISSUE THREAD

**Issue by ivanthejedy** [jdamata/terraform-provider-sonarqube#263]
Hi there,

SonarQube has provided API to copy profiles and deactivate rules for particular profiles.

Use case:
Embedded development in C++. Some rules could not be implemented due to the C++ dialect in a particular platform. Copying profiles from "Sonar Way" and "disabling" rules looks like a solution, to keep changes. 
Disabling rules look similar to Exclusion rules in sonar-project.properties file and provide sync between sonarlint and sonarscanner.

**Comment by tbutler-qontigo** [comment]
I don't think this is feasible - see discussions in https://github.com/jdamata/terraform-provider-sonarqube/issues/54 and https://github.com/jdamata/terraform-provider-sonarqube/pull/241

**Comment by ivanthejedy** [comment]
@tbutler-qontigo 

Can you suggest a way on how this use case is possible to implement most efficiently with the existing provider feature set?

**Comment by freeranger** [comment]
See my comment [here](https://github.com/jdamata/terraform-provider-sonarqube/issues/54#issuecomment-2388466065)
