### ISSUE TITLE
Question: SonarCloud support

### ISSUE THREAD

**Issue by diogonborges** [jdamata/terraform-provider-sonarqube#271]
Hi there,

Is there support for SonarCloud?

Or how far would it be to have it supported?

Thanks,
Diogo

**Comment by freeranger** [comment]
I don't think it does - you can try it but I have no experience of SonarCloud and I don't think the repo owner does either.
You could of course submit a PR with support for same for consideration

**Comment by jdamata** [comment]
I do not believe this provider supports sonarcloud and im not sure this provider is the right place for that. I imagine a new provider makes the most sense with the opportunity of having some code shared between the two with a shared lib.
