### ISSUE TITLE
Deactivate rule on a quality profile 

### ISSUE THREAD

**Issue by andrey-yakubovskiy** [jdamata/terraform-provider-sonarqube#54]
### Terraform Version
Terraform v1.0.9
on linux_amd64

### Affected Resource(s)
sonarqube_qualityprofile_deactivate_rule

### Expected Behavior
sonarqube_qualityprofile_deactivate_rule exists

### Actual Behavior
no way to deactivate rule on a quality profile.

### References
Sonar API documentation http://localhost:9000/web_api/api/qualityprofiles/deactivate_rule

**Comment by jdamata** [comment]
What's the use case for this? Quality profile rules are deactivated/deleted if they were initially created via terraform on destroy: https://github.com/jdamata/terraform-provider-sonarqube/blob/master/sonarqube/resource_sonarqube_qualityprofile_activate_rule.go#L112

**Comment by andrey-yakubovskiy** [comment]
as sonar user i should be able to manage quality profile rules using configuration as code approach according to my project requirements. if you have multiple application teams sharing single sonar installation they want to have their own quality profiles defined based on the built-in profiles but with their own customisations. each team would clone built-in quality profile for the language of their choice and use it as a base to further tailor it to their specific project conventions by deactivating certain rules.

**Comment by andrey-yakubovskiy** [comment]
we ship terraform module to our application teams to enable them to configure their sonar projects using config as code.  given this sonar json instructions application teams can create a clone of built-in quality profile and customise it further by enabling (supported by the provider) and disabling (not supported) quality profile rules

```
{
  "name": "My way",
  "language": "java",
  "organization": "default-organization",
  "parent_quality_profile": "",
  "copy_rules_from_profile": "Sonar way",
  "default": false,
  "rules": {
    "license_not_allowed": {
      "rule": "licensecheck:licensecheck.notallowedlicense",
      "severity": "BLOCKER"
    },
    "license_unknown": {
      "rule": "licensecheck:licensecheck.unlisted",
      "severity": "BLOCKER"
    }
  },
  "disable_rules": {
  },
  "projects": {
  }
}
```

and this is a snippet from our terraform module

```
resource "sonarqube_qualityprofile" "profile" {
  name       = local.profile_json.name
  language   = local.profile_json.language
  is_default = local.profile_json.default
  parent     = local.profile_json.parent_quality_profile
}

...

# rule activation using terraform provider
resource "sonarqube_qualityprofile_activate_rule" "profile_rules" {
  depends_on = [
    null_resource.profile
  ]
  for_each = local.profile_json.rules
  key      = sonarqube_qualityprofile.profile.key # .id also works
  rule     = each.value.rule
  severity = each.value.severity
  params   = try(each.value.params, "")
}
# disabling of rules not supported by the provider
resource "null_resource" "profile_disable_rules" {
  depends_on = [
    null_resource.profile
  ]
  for_each = local.profile_json.disable_rules
  triggers = {
    password   = var.sonar_password
    base_url   = var.sonar_url
    name       = local.profile_json.name
    language   = local.profile_json.language
    rule       = each.key
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = <<EOF
auth="admin:${self.triggers.password}"

echo "waiting for API..."
while ! curl --output /dev/null --head --fail -su $auth ${self.triggers.base_url}api/users/search? ; do sleep 10 && echo -n . ; done;

echo "Disabling rule ${each.key} key ${self.triggers.rule} for ${self.triggers.name}"
PROFILE=$(curl -su $auth -X GET ${self.triggers.base_url}api/qualityprofiles/search | \
  jq '.profiles[] | select((.name=="${self.triggers.name}") and (.language=="${self.triggers.language}")) | .key')
echo "Profile id: $PROFILE"
curl -su $auth -X POST ${self.triggers.base_url}api/qualityprofiles/deactivate_rule \
     -F "key=$PROFILE" -F "rule=${self.triggers.rule}"
EOF
  }
}
```

**Comment by tbutler-qontigo** [comment]
I think the problem here is the use of `copy_rules_from_profile` - doing that means terraform has no way of knowing what the rules are in the profile so I'm not sure how the provider could have the ability to delete them - as you say @jdamata rules created via terrraform will be deactivated on destroy.
Terraform does not support an explicit "delete" operation" - you'd have to create a resource to represent the delete rule...which does not make any sense really.

Our approach is to build a list of rules we want in a profile and `for_each` around them, getting one resource key per rule.
If we remove a rule from the list then it gets destroyed.
This list can be sourced from the default "Sonar Way" profile with the unwanted rules removed for example.

It's not an ideal solution by any means - you end up with a *lot* of resources in state...but I'm not sure there is a nicer way to work "the terraform way" and work "the Sonar Way" at the same time...

**Comment by ramblank-enbw** [comment]
I agree that this won't work for rules which were copied from a different quality profile, but it should be doable for inherited profiles. 
I think a sane way to do this would be to consider the sonarqube_qualityprofile_activate_rule resource to be changes to an inherited quality profile, e.g. if a rule was simply inherited from another quality profile ("api/rules/show" returns `"inherit": "INHERITED"`) the provider should consider it as non-existent.
Then a "deactivate" parameter could be added to the sonarqube_qualityprofile_activate_rule which deactivates an inherited rule (or a new _deactivate_rule resource). However the sonarqube API doesn't return quality profiles in the "actives" section of "api/rules/show" for which a rule would be inherited but was specifically deactivated.  Instead one could check whether "actives" includes the parent profile but not the current quality profile.

**Comment by mpas** [comment]
> I think the problem here is the use of `copy_rules_from_profile` - doing that means terraform has no way of knowing what the rules are in the profile so I'm not sure how the provider could have the ability to delete them - as you say @jdamata rules created via terrraform will be deactivated on destroy. Terraform does not support an explicit "delete" operation" - you'd have to create a resource to represent the delete rule...which does not make any sense really.
> 
> Our approach is to build a list of rules we want in a profile and `for_each` around them, getting one resource key per rule. If we remove a rule from the list then it gets destroyed. This list can be sourced from the default "Sonar Way" profile with the unwanted rules removed for example.
> 
> It's not an ideal solution by any means - you end up with a _lot_ of resources in state...but I'm not sure there is a nicer way to work "the terraform way" and work "the Sonar Way" at the same time...

@tbutler-qontigo could share a bit of code on how you do this?

**Comment by tbutler-qontigo** [comment]
I can't publish our code but this is approximately what we do (still using the "legacy" (preferred categorisations):

```
rules_url = "${var.sonar_core_serverbaseurl}/api/rules/search?asc=true&f=lang,severity,params&ps=500&statuses=READY&languages=${var.language}&is_template=false&types="

data "http" "security_hotspots" {
  url             = "${local.rules_url}SECURITY_HOTSPOT"
  request_headers = var.request_headers
}
...etc for other data categories
```
then combine them all into one ruleset, excluding the rules we don't want and map each rule as follows:
```
    rule["key"] => {
      severity : rule["severity"]
      params : try(join(";", [for param in rule["params"] : "${param.key}=${param.defaultValue}"]), null) # flatten the params object into key1=value1;key2=value2...
    }
```
and then for each profile we add that rule (unless it is an explicity defined one which we will add later):
```
resource "sonarqube_qualityprofile_activate_rule" "rulesets" {
  for_each = { for key, value in local.all_rulesets : key => value
    if !contains(keys(local.explicit_rules), key)  
  }
  key      = var.profile
  rule     = each.key
  severity = each.value.severity
  params   = each.value.params
}
```

**Comment by ivanthejedy** [comment]
@tbutler-qontigo 
Quite an interesting way. May I ask you to craft a `Guide` for the provider?

**Comment by freeranger** [comment]
That's not something I would have the bandwidth to do I'm afraid

**Comment by mpas** [comment]
@freeranger How do you exclude the rules that you do not want?

**Comment by freeranger** [comment]
> if !contains(keys(local.explicit_rules), key)

There are two different ways you could do this - in the example I gave which excludes explicit rules (because we add them later) you could also be excluding rules that are in a collection of rules that you just don't want.

Or `all_rulesets` is a combination of all of the rules we got using the `http` data provider - this could be filtering out the rules you don't want at that point

**Comment by Sam13** [comment]
I was now able to deactivate rules with feature from https://github.com/jdamata/terraform-provider-sonarqube/pull/356 in v0.16.19
