### ISSUE TITLE
Terraform plan fails to reach SonarQube

### ISSUE THREAD

**Issue by batizar** [jdamata/terraform-provider-sonarqube#65]
Hi,
I am testing this provider but I get this error when I run `terraform plan`. When I copy the same url to my browser it works fine.

Thanks.

```
Error: Unable to reach sonarqube: GET https://xxx:xxx@sonarqube.mycompany.com/api/server/version? giving up after 5 attempt(s)
```

### Terraform Version
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/jdamata/sonarqube v0.0.11

### Affected Resource(s)
- sonarqube_project

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.1"

  required_providers {
    sonarqube = {
      source = "jdamata/sonarqube"
    }
  }

  backend "azurerm" {
    resource_group_name  = "xxx"
    storage_account_name = "xxx"
    container_name       = "xxx"
    key                  = "xxx"
  }
}

provider "sonarqube" {
  user = "xxx"
  pass = "xxx"
  host = "https://sonarqube.mycompany.com"
}

resource "sonarqube_project" "test_project" {
  name       = "test-project-by-terraform"
  project    = "test-project-by-terraform"
  visibility = "public"
}

```

### Expected Behavior
Produce the plan

### Actual Behavior
Error failing to connect to SonarQube

**Comment by jdamata** [comment]
Is this still happening? This sounds like a networking issue. Where are you running terraform from?
