### ISSUE TITLE
Error on terraform init ( failed to retrieve authentication │ checksums for provider: 404 Not Found )

### ISSUE THREAD

**Issue by amaraldavi1** [jdamata/terraform-provider-sonarqube#73]
Hi there, I'm getting this error when running terraform init for this latest version.

### Terraform Version
`Terraform v1.1.7
on linux_amd64`

### Affected Resource(s)
Please list the resources as a list, for example:
- sonarqube_project

### Terraform Configuration Files
```
terraform {
  required_version = ">= 0.13"

  required_providers {
    sonarqube = {
      source = "jdamata/sonarqube"
    }
  }
}

provider "sonarqube" {
    user   = "admin"
    pass   = "admin" 
    host   = "http://127.0.0.1:9000"
    installed_version = "8.9.7"
    tls_insecure_skip_verify = true
}
```

### Expected Behavior
What should have happened?
Run the terraform init sucessfully.

### Actual Behavior
What actually happened?
Show the following error:

```
Error while installing jdamata/sonarqube v0.14.0: could not query provider registry for registry.terraform.io/jdamata/sonarqube: failed to retrieve authentication checksums for provider: 404 Not Found
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

**Comment by martiener1** [comment]
It looks like this was caused by a typo when version 0.0.14 was released.
https://github.com/jdamata/terraform-provider-sonarqube/releases
The last release had version "0.014" instead of the usual "0.0.14"

**Comment by ruriky** [comment]
Also provider version in terraform registry jumps from 0.0.13 to 0.14.0. Is that a mistake?
https://registry.terraform.io/providers/jdamata/sonarqube/0.14.0

**Comment by jdamata** [comment]
Yah that was definitely a typo on my part. I meant to publish v0.0.14. I can't find a way to "unpublish" that release though

**Comment by jdamata** [comment]
Tried to remove the tag/release, publish a new release and sync the terraform provider on the registry side but I can't get it deleted.

**Comment by jdamata** [comment]
I've gone ahead and pushed a release v0.14.0 which matches the version in terraform registry to hopefully get passed this error. I guess this provider is now on v0.14.0 :|
