### ISSUE TITLE
Terraform init failed for Latest Version 0.14.0

### ISSUE THREAD

**Issue by iankittomar** [jdamata/terraform-provider-sonarqube#78]
### Terraform Version
```hcl
Terraform v1.1.9
```

### Terraform command
```hcl
terraform init
```

### Expected Behavior
What should have happened?

Install the provider

### Actual Behavior
What actually happened?

│ Error: Failed to install provider

│ Error while installing jdamata/sonarqube v0.14.0: could not query provider registry for registry.terraform.io/jdamata/sonarqube: failed to retrieve authentication checksums for provider: 404 Not Found

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/34299541/165378551-0bb88cd4-f5c3-4118-884e-925d994a6307.png">

**Comment by jdamata** [comment]
No idea why this happened. Push release v0.14.1 which seems to be working. Sorry!
