### ISSUE TITLE
sonarqube_qualitygate_condition 

### ISSUE THREAD

**Issue by mahafrain** [jdamata/terraform-provider-sonarqube#85]
I am unable to add some quality gate metrics via terraform on SonarQube, specially the OWASP Dependency-Check ones(High Severity Vulnerabilities, Critical Severity Vulnerabilites etc.). 

Getting the following error:

Error: API returned an error: There is no metric with key=blocker_issues. (whereas it appears on the UI)

```
module "set_qualitygate_condition"{
  source = "../"

  qualitygate_name = "test"
  qualitygate_condition_list = [
    {
      metric = "vulnerabilities",
      "threshold" = "10",
      "op" = "GT"
    },
    {
      "metric" = "total_vulnerabilities",
      "threshold" = "20",
      "op" = "GT"
    },
    {
      "metric" = "vulnerable_dependencies",
      "threshold" = "10",
      "op" = "GT"
    },
    {
      "metric" = "blocker-issues",
      "threshold" = "3",
      "op" = "GT"
    }
  ]
  qualitygate_default = true
}
```

I was able to add the other three metrics via terraform with the same configuration as mentioned above. 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/90862317/176174442-5d03d997-d035-42ef-bf32-41d7e44d9a9b.png">

**Comment by aaniqtejani** [comment]
Some of the metrics are named differently in sonarqube code. To get there name you can setup a qualitygate by UI and then use this api link to get all the metrics info 

http://{sonarqube_URL}/api/qualitygates/show?name={qualitygate_name}

**Comment by jdamata** [comment]
@aaniqtejani  thank you for helping out
