### ISSUE TITLE
Combining projects?

### ISSUE THREAD

**Issue by mvantellingen** [jdamata/terraform-provider-sonarqube#9]
Hi @jdamata,

I've just stumbled on this project, awesome to see you are working on a terraform provider for sonarqube. I actually also started with this a couple of weeks ago and was wondering if we can perhaps join efforts?

See https://github.com/labd/terraform-provider-sonarqube

Let me know if you are interested

**Comment by jdamata** [comment]
Absolutely I'm interested.

@tiwood has done awesome work on this recently and should be included in whatever is decided.
