### ISSUE TITLE
Support to configure a permission_template as the default one

### ISSUE THREAD

**Issue by notarock** [jdamata/terraform-provider-sonarqube#96]
Hi there,

I am using this provider to provision quality gates, roles, permissions, etc.
I have created a permission template which enforces RBAC and I would like to set it as the default permission template to apply to new projects. I have searched the doc/code and did not find any way to do this as of right now.

### Terraform Version
```
$ terraform -v

Terraform v1.1.3
on linux_amd64
...
+ provider registry.terraform.io/jdamata/sonarqube v0.15.0
```

### Affected Resource(s)
- sonarqube_permission_template
- sonarqube_permission

### Expected Behavior
Being able to set a permission template as the default one to apply to new projects when they are created.

### Actual Behavior
No signs of being able to use the `permissions/set_default_template` api endpoint.

**Comment by jdamata** [comment]
Fixed in https://github.com/jdamata/terraform-provider-sonarqube/pull/102
