### ISSUE TITLE
Support for Sonar instance hosted on sub-path

### ISSUE THREAD

**Issue by NicolasFloquet** [jdamata/terraform-provider-sonarqube#98]
Hi there,

We're facing issues using your provider with a SonarQube instance hosted on a subpath.
If you need any help to fix this, we're open to provide a pull request

### Terraform Version
Terraform v1.2.5

### Affected Resource(s)
Global to provider

### Terraform Configuration Files
```hcl
provider "sonarqube" {
    token  = "<redacted>"
    host  = "https://quality-analysis.my-host.io/sonar/"
}

```

### Expected Behavior
We expect provider to work relatively to provided host.
For instance, version API should be called as following
`https://quality-analysis.my-host.io/sonar/api/server/version`

### Actual Behavior
Provider fails to call any API, because it's removing subpath when building API URL

### Steps to Reproduce
1. Run `terraform plan` on any sonarqube instance hosted on a subpath

**Comment by Momotoculteur** [comment]
Hey @jdamata,
Maybe you could have any hint on this ? :)

**Comment by max13-cloud** [comment]
Hi @jdamata,

Actually, line 106 you guys parse the host from provided configuration and then get the Host value from library which is not taking into account any subpath here. Could we append the path (Path value) or something? As said earlier, it is mandatory for us as our instance is hosted on a subpath "/sonar/.

Thanks a lot.

**Comment by jdamata** [comment]
Please try v0.15.4 https://github.com/jdamata/terraform-provider-sonarqube/pull/106

**Comment by max13-cloud** [comment]
Hi, thanks for taking care of our issue. Unfortunately, I think the fix is not enough since the path is overridden every time we need it. For example, I think we need something like:
sonarQubeURL := m.(*ProviderConfiguration).sonarQubeURL
**sonarQubeURL.Path +=** "api/user_tokens/generate"

Could you make those changes so we can give it a try on our end? 

Thanks a lot.

**Comment by jdamata** [comment]
@max13-cloud thank you for working on this. Version v0.15.5 should support path
